### ISSUE TITLE
Merge CHANGES files

### ISSUE THREAD

**Issue by hgrecco** [bors-ng/bors-ng#942] opened 2020-04-24 12:31 UTC
I have been using **bors** in many projects with great satisfaction. One of the major things that I enjoy is to devote some time to check all pending PRs, `bors r+` them (if they are ok) and forget. This reduces a lot the personal context switching.

However, there is one thing that frequently pops up: I have to resolve irrelevant merge conflict in the CHANGES. As you know the, CHANGES file (or similarly named) is just a listing of what has changed in each release. Therefore, it is very likely that a merge conflict occurs as most PR edit that single file in a single place (the end of the list). But this list is not code, not prose; just a list of things in which order (in principle) is not important and merging is trivial.

Therefore I would like to propose a that there is a way in bors to flag this file and if there is a conflict, it is automatically resolved by concatenating the changes of both PRs. Of course, this would be optional.

**Comment by notriddle** [comment] 2020-04-24 23:01
Duplicate of #927

**Closed** 2020-04-24 23:01 UTC
