### ISSUE TITLE
bors falsely failed despite of all CI checks are green 

### ISSUE THREAD

**Issue by lzutao** [bors-ng/bors-ng#1121] opened 2021-01-09 01:36 UTC
The problem is in a PR: https://github.com/xdg-rs/dirs/pull/48#issuecomment-757071387

All the CI checks are green, but bors told that "Build failed".
This could be a GitHub API error, although I'm not sure.
The `bors.toml` of the repo located at https://github.com/xdg-rs/dirs/blob/master/bors.toml

I'm happy to answer further questions about CI configuration if it could help.

P/S: I was going to create a topic on discourse forum. But after seeing some threads receive no replies,
I decided to open the issue here on GitHub. I'm sorry if that makes things inconvenient.
Thanks for all your works on bors the bot.

**Comment by notriddle** [comment] 2021-01-09 02:18
Duplicate of https://github.com/bors-ng/bors-ng/issues/1115

**Closed by notriddle** 2021-01-09 02:18 UTC
