### ISSUE TITLE
PR is stuck in running state

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#220] opened 2017-06-29 14:20 UTC
So today there were some problems with Travis, and they caused [this PR](https://github.com/intellij-rust/intellij-rust/pull/1394) to get stuck in the **Running** state, despite the fact that no build is in progress. 

Huh, it timed out just this very second, so now I am able to restart it! So, probably there's no issue here :) 

Hm, wait a second, so I've r+ this PR after the timeout, and now there are three PRs in a `waiting in queue` state, and no builds are in progress, so something is definitely wrong in the end! Here's the PR with links to the latest comment for the current moment:

https://github.com/intellij-rust/intellij-rust/pull/1396#issuecomment-311956270
https://github.com/intellij-rust/intellij-rust/pull/1395#issuecomment-311936720
https://github.com/intellij-rust/intellij-rust/pull/1394#issuecomment-311979609

**Comment by notriddle** [comment] 2017-06-29 14:55
It looks like 1396 is running. GitHub shows that the merge commit for it was created 26 minutes ago, and Travis says that it's been running for 10 minutes, so obviously Travis is running a bit slow right now.

**Comment by notriddle** [comment] 2017-06-29 15:02
OTOH, 1395 and 1394 aren't in the build queue, despite the fact that you did r+ them.

I'm working on a logging backend, exactly so that this kind of problem can be easier to track down (Heroku's built-in logger only keeps a few minutes worth of logs, which is pretty useless when I log in and find out that your batch processor crashed a half hour ago 😥).

**Comment by matklad** [comment] 2017-06-29 15:49
1396 is running because I've pushed a new commit to it and r+ed it again, after I've posted this issue :)

**Comment by matklad** [comment] 2017-06-29 15:54
>obviously Travis is running a bit slow right now

Not necessary, it's just that I have three configurations in the matrix, and Travis tests PRs twice, so there are six jobs that are scheduled before the bors jobs, so bors is just delayed. This delay is what the autotry issue is actually about.

**Comment by matklad** [comment] 2017-06-29 16:31
I've now manually canceled some builds, and forced pushed some branches to get the PRs merged, and looks like I've somehow messed up `push --force-with-lease`, so there may be some totally human produced weirdness in the logs as well :)

**Comment by notriddle** [comment] 2017-07-14 14:41
Duplicate of #206, anyway.

**Closed by notriddle** 2017-07-14 14:41 UTC
Labels: I-crash, I-intermittent
