### ISSUE TITLE
bors says "build failed" when actually it succeeded

### ISSUE THREAD

**Issue by RalfJung** [bors-ng/bors-ng#1129] opened 2021-01-15 21:16 UTC
I approved the PR at https://github.com/japaric/xargo/pull/310 and, as far as I can see, all the CI jobs are working correctly. Still, bors rejects the PR and says "build failed".

The link that it posts, https://github.com/japaric/xargo/runs/1711177465, goes to the skipped "ci" job. But it should just ignore that one and use the passed "ci" job. These two "ci" jobs are, I think, necessary with GHA as there is no other way to summarize the entire pipeline state into a single job.

**Comment by notriddle** [comment] 2021-01-15 23:54
> These two "ci" jobs are, I think, necessary

They aren't.

Bors-NG used to have a bug where it would fail to process skipped jobs. This gave the appearance that they were being totally ignored, but since it was actually giving a 500 result, it would cause the background polling task (which usually doesn't kick in, but sometimes is necessary) to totally fail and lock up the entire pipeline.

Bors considers the "skipped" task a failure now, instead of crashing. This is kind of a breaking change, but it's also much saner than the old behaviour, and simpler than just ignoring it (if they're both skipped, it would time out!).

So, just get rid of the "failure" job and it'll work again.

**Comment by notriddle** [comment] 2021-01-16 00:04
Honestly, if I'd realized there were tons of people copying this workflow hack from the rust-lang/\* repos (because homu apparently *does* totally ignore skipped jobs), I probably would've fixed the bug by making them get skipped as well.

But now the change is already made, and reverting it wouldn't be much better than forging ahead. And ignoring skipped jobs really does seem fragile.

**Comment by RalfJung** [comment] 2021-01-16 00:05
Okay. I don't understand why the skipped job exists in the first place (it exists for the homu-bors that rustc is using, no idea why), so removing it works for me.^^ Thanks!

> And ignoring skipped jobs really does seem fragile.

From my naive perspective, "skipped" means "please ignore / pretend it doesn't exist" -- that's what distinguishes it from "failed". But I am also a total GHA noob.

**Comment by notriddle** [comment] 2021-01-16 00:58
I don't generally like having "ignore this result" logic in bors-ng, because that seems like it'll wind up resulting in timeout failures. Nobody likes timeout failures, because they take a half hour to be reported.

> From my naive perspective, "skipped" means "please ignore / pretend it doesn't exist" -- that's what distinguishes it from "failed". So ignoring them IMO makes perfect sense. But I am also a total GHA noob.

[GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) says

> `jobs.<job_id>.needs` Identifies any jobs that must complete successfully before this job will run. It can be a string or array of strings. If a job fails, all jobs that need it are **skipped** unless the jobs use a conditional expression that causes the job to continue.

So, the meaning of "skipped" seems to be "prerequisite not met."

An important part is that "fails" propagate as "skips" through dependencies, and "skips" propagate as more "skips". It makes it look like the reason the distinction exists is to make root-cause analysis easier, since you know that the skipped jobs only failed because their dependencies failed, and the one that was actually marked as a "failure" is the one that caused it all.

In any case, the fix for your problem was to remove a bunch of code from your workflow file, so it seems like the new behaviour is closer to what you actually need.

---

p.s.

* Duplicate of #1121
* Duplicate of #1115

**Closed** 2021-02-18 01:27 UTC
