### ISSUE TITLE
Crash merging PR

### ISSUE THREAD

**Issue by palango** [bors-ng/bors-ng#432] opened 2018-06-20 10:54 UTC
We ran into the following crash. I think it hapened after the build succeded and bors tried to merge into master.

```
{{:badmatch, {:error, :push}},
 [{BorsNG.GitHub, :push!, 3,
   [file: 'lib/github/github.ex', line: 63]},
  {BorsNG.Worker.Batcher, :complete_batch, 3,
   [file: 'lib/worker/batcher.ex', line: 381]},
  {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
   [file: 'lib/worker/batcher.ex', line: 368]},
  {BorsNG.Worker.Batcher, :handle_cast, 2,
   [file: 'lib/worker/batcher.ex', line: 77]},
  {:gen_server, :try_dispatch, 4,
   [file: 'gen_server.erl', line: 616]},
  {:gen_server, :handle_msg, 6,
   [file: 'gen_server.erl', line: 686]},
  {:proc_lib, :init_p_do_apply, 3,
   [file: 'proc_lib.erl', line: 247]}]}
```

**Comment by JensRantil** [comment] 2018-06-20 12:20
Looks like there's been a few [similar issue submissions](https://github.com/bors-ng/bors-ng/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%3Apush%21). Could this be a duplicate of any of those?

**Comment by vlad20012** [comment] 2018-10-18 19:18
I've get something similar [here]({{:badmatch, {:error, :get_branch}},
 [
   {BorsNG.GitHub, :get_branch!, 2,
    [file: 'lib/github/github.ex', line: 70]},
   {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 247]},
   {BorsNG.Worker.Batcher, :poll_, 1,
    [file: 'lib/worker/batcher.ex', line: 199]},
   {BorsNG.Worker.Batcher, :handle_info, 2,
    [file: 'lib/worker/batcher.ex', line: 181]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]})
```
{{:badmatch, {:error, :get_branch}},
 [
   {BorsNG.GitHub, :get_branch!, 2,
    [file: 'lib/github/github.ex', line: 70]},
   {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 247]},
   {BorsNG.Worker.Batcher, :poll_, 1,
    [file: 'lib/worker/batcher.ex', line: 199]},
   {BorsNG.Worker.Batcher, :handle_info, 2,
    [file: 'lib/worker/batcher.ex', line: 181]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

**Comment by notriddle** [comment] 2018-11-29 23:51
Nope, didn't fix it. Happened again on Mir's repo.

**Comment by tommilligan** [comment] 2021-07-01 11:03
Hey @palango , I believe this can be now closed as fixed by #1273. Please take a look and verify if it covers your use case, or provide more details if not.

bors now provides generic error handling if github rejects merging the tested commit into the parent branch.

**Comment by palango** [comment] 2021-07-01 11:05
@tommilligan Thanks for the reply. I cannot test this any more since the repo doesn't exist any more. Feel free to close.

**Comment by tommilligan** [comment] 2021-07-01 12:26
Thank - if we can't reproduce and the issue is no longer relevant to you, could you close? I'm just trying to tidy up issues that don't require further action, but am not a maintainer so don't have the power to close your issue :slightly_smiling_face: 

If you think this still requires attention, then of course please leave open.

**Closed** 2021-07-01 12:26 UTC
