### ISSUE TITLE
bors: try does not start a build

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#317] opened 2017-10-17 14:29 UTC
For some reasons, `bors: try` does not work for this pull request: https://github.com/intellij-rust/intellij-rust/pull/1862#issuecomment-337248030

Bors just replies with "Not awaiting review", without scheduling the build :(

**Comment by Freyskeyd** [comment] 2017-10-22 13:38
I got the same and it timed out after some times.

**Comment by notriddle** [comment] 2017-12-13 23:53
@matklad I notice that your try command [did start a build, eventually](https://github.com/intellij-rust/intellij-rust/commit/6bdcd90ad9069374a1f4fbf4fa79c3aab2573966). I think it might've just been delayed webhooks.

There were further confused by #323. I've seen a lot more people successfully keeping track of the trying and running states since that was put in, like [here](https://github.com/CS450-ECE461/fall2017-team5-apiserver/pull/136#issuecomment-351538074).

So I'm going to close this.

**Closed by notriddle** 2017-12-13 23:53 UTC
Labels: I-bustage

**Comment by andschwa** [comment] 2018-09-14 22:47
I also ran into this. The cause was similar: I transitioned Bors to an upstream repo after testing on my fork; on my fork, my CI webhook had push events (they're the default), but the same hook on the upstream repo had been set only to PRs. So `bors try` pushed to the trying branch, and then CI didn't build. I wondered what was wrong and tried `bors try` again; at this point it started reporting "Not awaiting review" which is _not at all_ what it meant.

If possible, we should fix the error message in this case to something like "Already waiting for build, not trying again." or something.
