### ISSUE TITLE
A failing check_self can kill the GenServer

### ISSUE THREAD

**Issue by zli-simspace** [bors-ng/bors-ng#1085] opened 2020-11-19 19:44 UTC
I'm seeing periodic restart in our (private) Bors server. A number of them are preceded by a failed `self_check``

```
[error] GenServer #PID<0.20129.2> terminating
** (MatchError) no match of right hand side value: #PID<0.20128.2>
    (bors) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
    (bors) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:poll, :repeat}
[info] Running BorsNG.Endpoint with cowboy <version> at <ip>
```

I know the self-check error itself is normal but from the timestamps, it does seem to be the trigger for the Bors restart. It could still be a number of other things though.

Sometimes, before the last line indicating a restart, there's also

```
pid=<0.8508.0> [error] GenServer BorsNG.Worker.Batcher.Registry terminating
** (stop) exited in: GenServer.call(BorsNG.Worker.Batcher.Supervisor, {:start_child, {{BorsNG.Worker.Batcher, :start_link, 'l'}, :permanent, 5000, :worker, [BorsNG.Worker.Batcher]}}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (bors) lib/worker/batcher/registry.ex:50: BorsNG.Worker.Batcher.Registry.do_start/1
    (bors) lib/worker/batcher/registry.ex:55: BorsNG.Worker.Batcher.Registry.start_and_insert/2
    (bors) lib/worker/batcher/registry.ex:83: BorsNG.Worker.Batcher.Registry.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:DOWN, #Reference<0.1078022152.3600285698.175770>, :process, #PID<0.14783.0>, :shutdown}
```

I came across this as I'm still looking into why sometimes preflight polling stops for no apparent reason. And I think this is indeed the cause. (One way to help with that is to persist the preflight poll into the database. I kind of regret not having spent my time implementing that instead of trying to track this bug.)

I don't yet know why a failed self_check would end the main/initial GenServer.

I'm also trying to see if others are seeing this as well or not (grep for `Running BorsNG.Endpoint with cowboy` in the logs).

**Comment by notriddle** [comment] 2020-11-19 20:56
I would try to track down why the self_check is failing in the first place.

**Comment by basvandijk** [comment] 2020-11-24 22:52
> I came across this as I'm still looking into why sometimes preflight polling stops for no apparent reason.

I have the same problem with my private bors instance. Many people in our org issue a `bors merge` before the required `pr_status` has been received causing bors to comment the expected:

> 🕐 Waiting for PR status (Github check) to be set, probably by CI. Bors will automatically try to run when all required PR statuses are set.

However, after the required `pr_status` has been received bors doesn't batch the PR for merging. Instead we have to issue another `bors merge` after bors does successfully batch the PR. 

I also see many `BorsNG.Worker.Batcher.check_self` errors in our logs.

**Comment by zli-simspace** [comment] 2020-11-25 14:32
@notriddle does the Registry crash often? I see a lot of `check_self` errors in our logs but not all of them result in a reset.

(I'll look into this more but may be a while before I can seriously dig into it.)

@basvandijk Do you also see a `Access BorsNG.Endpoint at` in your logs in these cases? The `check_self` error itself shouldn't make it need a second `bors merge`, only the Bors server restart does.

**Comment by basvandijk** [comment] 2020-11-25 15:04
>Do you also see a Access BorsNG.Endpoint at in your logs in these cases? 

Yes I'm seeing the following around 10 times per day:

```
Nov 25 01:03:36 bors c846ecc8989d[858]: 01:03:36.359 pid=<0.28512.5> [error] GenServer BorsNG.Worker.BranchDeleter terminating
Nov 25 01:03:36 bors c846ecc8989d[858]: ** (MatchError) no match of right hand side value: false
Nov 25 01:03:36 bors c846ecc8989d[858]:     (bors) lib/worker/branch_deleter.ex:76: BorsNG.Worker.BranchDeleter.delete_branch/2
Nov 25 01:03:36 bors c846ecc8989d[858]:     (bors) lib/worker/branch_deleter.ex:46: BorsNG.Worker.BranchDeleter.handle_cast/2
Nov 25 01:03:36 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Nov 25 01:03:36 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Nov 25 01:03:36 bors c846ecc8989d[858]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Nov 25 01:03:36 bors c846ecc8989d[858]: Last message: {:"$gen_cast", {:delete, %BorsNG.Database.Patch{__meta__: #Ecto.Schema.Metadata<:loaded, "patches">, author: #Ecto.Association.NotLoaded<association :author is not loaded>, author_id:>
Nov 25 01:03:36 bors c846ecc8989d[858]: 01:03:36.365 pid=<0.30646.5> [info] Running BorsNG.Endpoint with cowboy 1.1.2 at 0.0.0.0:4000 (http)
Nov 25 01:03:36 bors c846ecc8989d[858]: 01:03:36.367 pid=<0.2016.0> [info] Access BorsNG.Endpoint at https://XXXXXXXXXXXXXXX
```

I also get many complaints from our users that after the `Waiting for PR status` message from bors their PRs are stuck and the only way to unstuck them is to issue another `bors merge`.

**Comment by basvandijk** [comment] 2020-11-25 15:10
Actually the previous was a bad example because it didn't include the failing `check_self`. Here's the most recent failure from my log which does include a failing `check_self`:
```
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.606 pid=<0.5073.6> [error] GenServer #PID<0.5073.6> terminating
Nov 25 12:54:39 bors c846ecc8989d[858]: ** (MatchError) no match of right hand side value: #PID<0.4886.6>
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Nov 25 12:54:39 bors c846ecc8989d[858]: Last message: {:poll, :repeat}
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.610 pid=<0.5074.6> [error] GenServer #PID<0.5074.6> terminating
Nov 25 12:54:39 bors c846ecc8989d[858]: ** (MatchError) no match of right hand side value: #PID<0.4886.6>
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Nov 25 12:54:39 bors c846ecc8989d[858]: Last message: {:poll, :repeat}
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.613 pid=<0.5075.6> [error] GenServer #PID<0.5075.6> terminating
Nov 25 12:54:39 bors c846ecc8989d[858]: ** (MatchError) no match of right hand side value: #PID<0.4886.6>
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Nov 25 12:54:39 bors c846ecc8989d[858]: Last message: {:poll, :repeat}
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.613 pid=<0.4888.6> [error] GenServer #PID<0.4888.6> terminating
Nov 25 12:54:39 bors c846ecc8989d[858]: ** (MatchError) no match of right hand side value: #PID<0.4886.6>
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:1206: BorsNG.Worker.Batcher.check_self/1
Nov 25 12:54:39 bors c846ecc8989d[858]:     (bors) lib/worker/batcher.ex:231: BorsNG.Worker.Batcher.handle_info/2
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Nov 25 12:54:39 bors c846ecc8989d[858]:     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Nov 25 12:54:39 bors c846ecc8989d[858]: Last message: {:poll, :repeat}
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.624 pid=<0.5281.6> [info] Running BorsNG.Endpoint with cowboy 1.1.2 at 0.0.0.0:4000 (http)
Nov 25 12:54:39 bors c846ecc8989d[858]: 12:54:39.627 pid=<0.2016.0> [info] Access BorsNG.Endpoint at https://XXXXXXXXXX
```

**Comment by dieend** [comment] 2020-12-02 01:54
We encounter this fairly often in our private fork:
![image](https://user-images.githubusercontent.com/1404443/100818044-33e09c80-33fe-11eb-8df5-3341924bf9a9.png)

**Comment by notriddle** [comment] 2020-12-03 18:18
Can you try merging https://github.com/bors-ng/bors-ng/pull/1093 into your private fork? I'm not sure if this is the cause or not, but it seems plausible that it is.

**Comment by dieend** [comment] 2020-12-04 00:54
@notriddle May I get an understanding of why we want to delete/cancel all waiting/running batch?

In our private fork, we intentionally comment the cancel part out because it's such a hassle when it crashed and 10s of PRs get canceled and there is no trail of what PRs are being canceled. There are cases where our user left a PR for 2 days after "bors r+" not realizing that their PR was still not merged because the bors crashed when their PR already put in the queue.

I think what I can cherry-pick is removing the `start_and_insert` line.

**Comment by notriddle** [comment] 2020-12-04 02:27
> May I get an understanding of why we want to delete/cancel all waiting/running batch?

It's difficult to be sure which batch caused it to crash, and we don't want to crash loop. If an Erlang supervisor detects that it's restarting a process too quickly, it will fire a circuit breaker and crash the entire application.

> I think what I can cherry-pick is removing the start_and_insert line.

You'll also want to make sure that you cherry-pick the `if names[project_id] == pid` part. That's to ensure that, if two instances wind up running at the same time, they won't remove each others' entry in the name map.

**Comment by dieend** [comment] 2020-12-08 18:52
I tried cherry-picking #1093 and deployed it to our private instance but the error + restart is still happening.

**Comment by notriddle** [comment] 2020-12-08 22:53
@dieend Okay, try applying https://github.com/bors-ng/bors-ng/pull/1097 to your version and see if that helps.

**Comment by dieend** [comment] 2020-12-11 07:30
@notriddle hi, I deployed #1097 to our cluster, the server seems still being restarted.

Here is how the log looks like when it happened. All the terminating errors are caused by check_self, but as you can see it doesn't always end up as restarting the cowboy.
![image](https://user-images.githubusercontent.com/1404443/101875172-0652cc00-3b3f-11eb-9e31-9b76ba73a7f1.png)


Also, there is a crash log recorded as shutdown when this happened.
![image](https://user-images.githubusercontent.com/1404443/101875245-26828b00-3b3f-11eb-9b02-becef2da22cd.png)

Ipersist the preflight poll into the database

**Comment by notriddle** [comment] 2020-12-11 16:52
Does it always happen right after a Postgrex connection error like that?

**Comment by dieend** [comment] 2020-12-12 03:41
@notriddle That looks like the case. We only have logs for the last 2 days, so at least since I picked #1097 it always has Postgrex connection error.

**Comment by notriddle** [comment] 2020-12-12 05:08
Okay, so two questions:

1. What’s your POOL_SIZE environment variable set to in bors?

2. What’s your max_connections set to in postgresql?

**Comment by dieend** [comment] 2020-12-31 00:55
@notriddle we use pgbouncer with 10 pools with standalone RDS behind it. The maximum connection should be high enough for all of it.

I ended up making this to fix it: https://github.com/bors-ng/bors-ng/pull/1116

**Closed** 2020-12-31 17:16 UTC

**Comment by joshribakoff** [comment] 2021-02-26 02:08
an event consumer in prod is broken, and bors isn't merging the fix here after the CI checks passed https://github.com/brexhq/credit_card/pull/32289
